// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: tweets.proto

package tweets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TweetsServiceClient is the client API for TweetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetsServiceClient interface {
	GetTweetsByUsers(ctx context.Context, in *GetTweetsRequest, opts ...grpc.CallOption) (*GetTweetsResponse, error)
	AddNewTweet(ctx context.Context, in *AddTweetRequest, opts ...grpc.CallOption) (*AddTweetResponse, error)
}

type tweetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetsServiceClient(cc grpc.ClientConnInterface) TweetsServiceClient {
	return &tweetsServiceClient{cc}
}

func (c *tweetsServiceClient) GetTweetsByUsers(ctx context.Context, in *GetTweetsRequest, opts ...grpc.CallOption) (*GetTweetsResponse, error) {
	out := new(GetTweetsResponse)
	err := c.cc.Invoke(ctx, "/tweets.TweetsService/GetTweetsByUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsServiceClient) AddNewTweet(ctx context.Context, in *AddTweetRequest, opts ...grpc.CallOption) (*AddTweetResponse, error) {
	out := new(AddTweetResponse)
	err := c.cc.Invoke(ctx, "/tweets.TweetsService/AddNewTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetsServiceServer is the server API for TweetsService service.
// All implementations must embed UnimplementedTweetsServiceServer
// for forward compatibility
type TweetsServiceServer interface {
	GetTweetsByUsers(context.Context, *GetTweetsRequest) (*GetTweetsResponse, error)
	AddNewTweet(context.Context, *AddTweetRequest) (*AddTweetResponse, error)
	mustEmbedUnimplementedTweetsServiceServer()
}

// UnimplementedTweetsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTweetsServiceServer struct {
}

func (UnimplementedTweetsServiceServer) GetTweetsByUsers(context.Context, *GetTweetsRequest) (*GetTweetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTweetsByUsers not implemented")
}
func (UnimplementedTweetsServiceServer) AddNewTweet(context.Context, *AddTweetRequest) (*AddTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewTweet not implemented")
}
func (UnimplementedTweetsServiceServer) mustEmbedUnimplementedTweetsServiceServer() {}

// UnsafeTweetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetsServiceServer will
// result in compilation errors.
type UnsafeTweetsServiceServer interface {
	mustEmbedUnimplementedTweetsServiceServer()
}

func RegisterTweetsServiceServer(s grpc.ServiceRegistrar, srv TweetsServiceServer) {
	s.RegisterService(&TweetsService_ServiceDesc, srv)
}

func _TweetsService_GetTweetsByUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTweetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServiceServer).GetTweetsByUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tweets.TweetsService/GetTweetsByUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServiceServer).GetTweetsByUsers(ctx, req.(*GetTweetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetsService_AddNewTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServiceServer).AddNewTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tweets.TweetsService/AddNewTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServiceServer).AddNewTweet(ctx, req.(*AddTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TweetsService_ServiceDesc is the grpc.ServiceDesc for TweetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TweetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tweets.TweetsService",
	HandlerType: (*TweetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTweetsByUsers",
			Handler:    _TweetsService_GetTweetsByUsers_Handler,
		},
		{
			MethodName: "AddNewTweet",
			Handler:    _TweetsService_AddNewTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tweets.proto",
}
